# Form implementation generated from reading ui file 'Staff.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Staff(object):
    def setupUi(self, Staff):
        Staff.setObjectName("Staff")
        Staff.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Staff.resize(920, 650)
        Staff.setFixedSize(920,650)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Staff.setFont(font)
        Staff.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Staff.setWindowIcon(icon)
        Staff.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        Staff.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=Staff)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 70, 891, 481))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 10, 121, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(11, 48, 84);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 10, 121, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 10, 121, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 10, 121, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(780, 570, 121, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(860, 10, 41, 41))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(221, 221, 221);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(152, 152, 152);\n"
"}")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "icon-filter.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setObjectName("pushButton_7")
        Staff.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Staff)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menubar.setObjectName("menubar")
        Staff.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Staff)
        self.statusbar.setObjectName("statusbar")
        Staff.setStatusBar(self.statusbar)

        self.retranslateUi(Staff)
        QtCore.QMetaObject.connectSlotsByName(Staff)

    def retranslateUi(self, Staff):
        _translate = QtCore.QCoreApplication.translate
        Staff.setWindowTitle(_translate("Staff", "Приложение"))
        self.pushButton.setText(_translate("Staff", "Должности"))
        self.pushButton_2.setText(_translate("Staff", "Сотрудники"))
        self.pushButton_3.setText(_translate("Staff", "Заказы"))
        self.pushButton_4.setText(_translate("Staff", "Клиенты"))
        self.pushButton_5.setText(_translate("Staff", "Товары"))
        self.pushButton_6.setText(_translate("Staff", "Добавить"))
