# Form implementation generated from reading ui file 'FormShowZakaz.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Show_Zakaz(object):
    def setupUi(self, Form_Show_Zakaz):
        Form_Show_Zakaz.setObjectName("Form_Show_Zakaz")
        Form_Show_Zakaz.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Show_Zakaz.resize(400, 597)
        Form_Show_Zakaz.setFixedSize(400,597)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Show_Zakaz.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Show_Zakaz.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form_Show_Zakaz)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form_Show_Zakaz)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 181, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form_Show_Zakaz)
        self.label_3.setGeometry(QtCore.QRect(20, 225, 181, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=Form_Show_Zakaz)
        self.label_5.setGeometry(QtCore.QRect(20, 510, 181, 16))
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(parent=Form_Show_Zakaz)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setGeometry(QtCore.QRect(20, 540, 361, 24))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.tableView = QtWidgets.QTableView(parent=Form_Show_Zakaz)
        self.tableView.setGeometry(QtCore.QRect(20, 260, 361, 171))
        self.tableView.setObjectName("tableView")
        self.label_4 = QtWidgets.QLabel(parent=Form_Show_Zakaz)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 181, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=Form_Show_Zakaz)
        self.label_6.setGeometry(QtCore.QRect(20, 440, 181, 16))
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Show_Zakaz)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Form_Show_Zakaz)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 120, 361, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=Form_Show_Zakaz)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 190, 361, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=Form_Show_Zakaz)
        self.textEdit_4.setEnabled(False)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 470, 361, 31))
        self.textEdit_4.setObjectName("textEdit_4")

        self.retranslateUi(Form_Show_Zakaz)
        QtCore.QMetaObject.connectSlotsByName(Form_Show_Zakaz)

    def retranslateUi(self, Form_Show_Zakaz):
        _translate = QtCore.QCoreApplication.translate
        Form_Show_Zakaz.setWindowTitle(_translate("Form_Show_Zakaz", "Просмотр записи"))
        self.label.setText(_translate("Form_Show_Zakaz", "Название клиента"))
        self.label_2.setText(_translate("Form_Show_Zakaz", "Сотрудник"))
        self.label_3.setText(_translate("Form_Show_Zakaz", "Товары"))
        self.label_5.setText(_translate("Form_Show_Zakaz", "Дата"))
        self.dateEdit.setDisplayFormat(_translate("Form_Show_Zakaz", "dd.MM.yyyy"))
        self.label_4.setText(_translate("Form_Show_Zakaz", "Статус"))
        self.label_6.setText(_translate("Form_Show_Zakaz", "Сумма"))
