# Form implementation generated from reading ui file 'FormInsertProduct.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Product(object):
    def setupUi(self, Form_Product):
        Form_Product.setObjectName("Form_Product")
        Form_Product.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Product.resize(400, 300)
        Form_Product.setFixedSize(400,300)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Product.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Product.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form_Product)
        self.label.setGeometry(QtCore.QRect(20, 40, 181, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Product)
        self.textEdit.setGeometry(QtCore.QRect(20, 80, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Product)
        self.pushButton.setGeometry(QtCore.QRect(150, 240, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=Form_Product)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 181, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Form_Product)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 170, 361, 31))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Form_Product)
        QtCore.QMetaObject.connectSlotsByName(Form_Product)

    def retranslateUi(self, Form_Product):
        _translate = QtCore.QCoreApplication.translate
        Form_Product.setWindowTitle(_translate("Form_Product", "Добавление записи"))
        self.label.setText(_translate("Form_Product", "Наименование товара"))
        self.pushButton.setText(_translate("Form_Product", "Добавить"))
        self.label_2.setText(_translate("Form_Product", "Цена"))
