# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_products(object):
    def setupUi(self, products):
        products.setObjectName("products")
        products.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        products.resize(920, 650)
        products.setFixedSize(920,650)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        products.setFont(font)
        products.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        products.setWindowIcon(icon)
        products.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        products.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=products)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 70, 891, 481))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 10, 121, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 10, 121, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 10, 121, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 10, 121, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(11, 48, 84);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(780, 570, 121, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        products.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=products)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menubar.setObjectName("menubar")
        products.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=products)
        self.statusbar.setObjectName("statusbar")
        products.setStatusBar(self.statusbar)

        self.retranslateUi(products)
        QtCore.QMetaObject.connectSlotsByName(products)

    def retranslateUi(self, products):
        _translate = QtCore.QCoreApplication.translate
        products.setWindowTitle(_translate("products", "Приложение"))
        self.pushButton.setText(_translate("products", "Должности"))
        self.pushButton_2.setText(_translate("products", "Сотрудники"))
        self.pushButton_3.setText(_translate("products", "Заказы"))
        self.pushButton_4.setText(_translate("products", "Клиенты"))
        self.pushButton_5.setText(_translate("products", "Товары"))
        self.pushButton_6.setText(_translate("products", "Добавить"))
