# Form implementation generated from reading ui file 'FormUpdateZakaz.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Update_Zakaz(object):
    def setupUi(self, Form_Update_Zakaz):
        Form_Update_Zakaz.setObjectName("Form_Update_Zakaz")
        Form_Update_Zakaz.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Update_Zakaz.resize(400, 608)
        Form_Update_Zakaz.setFixedSize(400,608)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Update_Zakaz.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Update_Zakaz.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form_Update_Zakaz)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Update_Zakaz)
        self.pushButton.setGeometry(QtCore.QRect(140, 560, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=Form_Update_Zakaz)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 181, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form_Update_Zakaz)
        self.label_3.setGeometry(QtCore.QRect(20, 245, 181, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=Form_Update_Zakaz)
        self.label_5.setGeometry(QtCore.QRect(20, 470, 181, 16))
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(parent=Form_Update_Zakaz)
        self.dateEdit.setGeometry(QtCore.QRect(20, 500, 361, 24))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox = QtWidgets.QComboBox(parent=Form_Update_Zakaz)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 361, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Form_Update_Zakaz)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 200, 361, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form_Update_Zakaz)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 240, 51, 32))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(11, 48, 84);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableView = QtWidgets.QTableView(parent=Form_Update_Zakaz)
        self.tableView.setGeometry(QtCore.QRect(20, 280, 361, 171))
        self.tableView.setObjectName("tableView")
        self.label_4 = QtWidgets.QLabel(parent=Form_Update_Zakaz)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 181, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Form_Update_Zakaz)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 130, 361, 26))
        self.comboBox_3.setObjectName("comboBox_3")

        self.retranslateUi(Form_Update_Zakaz)
        QtCore.QMetaObject.connectSlotsByName(Form_Update_Zakaz)

    def retranslateUi(self, Form_Update_Zakaz):
        _translate = QtCore.QCoreApplication.translate
        Form_Update_Zakaz.setWindowTitle(_translate("Form_Update_Zakaz", "Форма обновления записи"))
        self.label.setText(_translate("Form_Update_Zakaz", "Название"))
        self.pushButton.setText(_translate("Form_Update_Zakaz", "Обновить"))
        self.label_2.setText(_translate("Form_Update_Zakaz", "Сотрудник"))
        self.label_3.setText(_translate("Form_Update_Zakaz", "Товары"))
        self.label_5.setText(_translate("Form_Update_Zakaz", "Дата"))
        self.dateEdit.setDisplayFormat(_translate("Form_Update_Zakaz", "dd.MM.yyyy"))
        self.pushButton_2.setText(_translate("Form_Update_Zakaz", "+"))
        self.label_4.setText(_translate("Form_Update_Zakaz", "Статус"))
