# Form implementation generated from reading ui file 'FormUpdateClient.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Update_Client(object):
    def setupUi(self, Form_Update_Client):
        Form_Update_Client.setObjectName("Form_Update_Client")
        Form_Update_Client.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Update_Client.resize(400, 670)
        Form_Update_Client.setFixedSize(400,670)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Update_Client.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Update_Client.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Update_Client)
        self.pushButton.setGeometry(QtCore.QRect(140, 630, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 181, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 140, 361, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 181, 16))
        self.label_3.setObjectName("label_3")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 220, 361, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 181, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 290, 361, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_5 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_5.setGeometry(QtCore.QRect(20, 330, 181, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_5 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 360, 361, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 430, 361, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_6 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_6.setGeometry(QtCore.QRect(20, 400, 181, 16))
        self.label_6.setObjectName("label_6")
        self.textEdit_7 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 500, 361, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_7 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_7.setGeometry(QtCore.QRect(20, 470, 181, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit_8 = QtWidgets.QTextEdit(parent=Form_Update_Client)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 570, 361, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_8 = QtWidgets.QLabel(parent=Form_Update_Client)
        self.label_8.setGeometry(QtCore.QRect(20, 540, 181, 16))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form_Update_Client)
        QtCore.QMetaObject.connectSlotsByName(Form_Update_Client)

    def retranslateUi(self, Form_Update_Client):
        _translate = QtCore.QCoreApplication.translate
        Form_Update_Client.setWindowTitle(_translate("Form_Update_Client", "Форма обновления записи"))
        self.label.setText(_translate("Form_Update_Client", "Название"))
        self.pushButton.setText(_translate("Form_Update_Client", "Обновить"))
        self.label_2.setText(_translate("Form_Update_Client", "Адрес проживания"))
        self.label_3.setText(_translate("Form_Update_Client", "Контактное лицо"))
        self.label_4.setText(_translate("Form_Update_Client", "Почта"))
        self.label_5.setText(_translate("Form_Update_Client", "Договор"))
        self.label_6.setText(_translate("Form_Update_Client", "ИНН"))
        self.label_7.setText(_translate("Form_Update_Client", "Телефон"))
        self.label_8.setText(_translate("Form_Update_Client", "Примечание"))
