# Form implementation generated from reading ui file 'FormFilterStaff.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Filter_Staff(object):
    def setupUi(self, Form_Filter_Staff):
        Form_Filter_Staff.setObjectName("Form_Filter_Staff")
        Form_Filter_Staff.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Filter_Staff.resize(400, 243)
        Form_Filter_Staff.setFixedSize(400,243)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Filter_Staff.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Filter_Staff.setWindowIcon(icon)
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Filter_Staff)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Filter_Staff)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form_Filter_Staff)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 200, 113, 32))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(parent=Form_Filter_Staff)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(20, 140, 361, 31))
        self.comboBox.setObjectName("comboBox")
        self.radioButton = QtWidgets.QRadioButton(parent=Form_Filter_Staff)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Form_Filter_Staff)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 110, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Form_Filter_Staff)
        QtCore.QMetaObject.connectSlotsByName(Form_Filter_Staff)

    def retranslateUi(self, Form_Filter_Staff):
        _translate = QtCore.QCoreApplication.translate
        Form_Filter_Staff.setWindowTitle(_translate("Form_Filter_Staff", "Фильтр"))
        self.pushButton.setText(_translate("Form_Filter_Staff", "Применить"))
        self.pushButton_2.setText(_translate("Form_Filter_Staff", "Сбросить"))
        self.radioButton.setText(_translate("Form_Filter_Staff", "ФИО"))
        self.radioButton_2.setText(_translate("Form_Filter_Staff", "Должность"))
