# Form implementation generated from reading ui file 'FormFilterZakaz.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Filter_Zakaz(object):
    def setupUi(self, Form_Filter_Zakaz):
        Form_Filter_Zakaz.setObjectName("Form_Filter_Zakaz")
        Form_Filter_Zakaz.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Filter_Zakaz.setEnabled(True)
        Form_Filter_Zakaz.resize(401, 411)
        Form_Filter_Zakaz.setFixedSize(400,411)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Filter_Zakaz.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Filter_Zakaz.setWindowIcon(icon)
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Filter_Zakaz)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 130, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Filter_Zakaz)
        self.pushButton.setGeometry(QtCore.QRect(40, 350, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form_Filter_Zakaz)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 350, 113, 32))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(parent=Form_Filter_Zakaz)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(20, 210, 361, 26))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(parent=Form_Filter_Zakaz)
        self.label_4.setGeometry(QtCore.QRect(180, 290, 31, 16))
        self.label_4.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(parent=Form_Filter_Zakaz)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setGeometry(QtCore.QRect(20, 280, 161, 31))
        self.dateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=Form_Filter_Zakaz)
        self.dateEdit_2.setEnabled(False)
        self.dateEdit_2.setGeometry(QtCore.QRect(210, 280, 161, 31))
        self.dateEdit_2.setDate(QtCore.QDate(2024, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.spinBox = QtWidgets.QSpinBox(parent=Form_Filter_Zakaz)
        self.spinBox.setEnabled(False)
        self.spinBox.setGeometry(QtCore.QRect(20, 50, 361, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.radioButton = QtWidgets.QRadioButton(parent=Form_Filter_Zakaz)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 161, 20))
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Form_Filter_Zakaz)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 100, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Form_Filter_Zakaz)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 180, 100, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=Form_Filter_Zakaz)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 250, 151, 20))
        self.radioButton_4.setObjectName("radioButton_4")

        self.retranslateUi(Form_Filter_Zakaz)
        QtCore.QMetaObject.connectSlotsByName(Form_Filter_Zakaz)

    def retranslateUi(self, Form_Filter_Zakaz):
        _translate = QtCore.QCoreApplication.translate
        Form_Filter_Zakaz.setWindowTitle(_translate("Form_Filter_Zakaz", "Фильтр"))
        self.pushButton.setText(_translate("Form_Filter_Zakaz", "Применить"))
        self.pushButton_2.setText(_translate("Form_Filter_Zakaz", "Сбросить"))
        self.label_4.setText(_translate("Form_Filter_Zakaz", "по"))
        self.radioButton.setText(_translate("Form_Filter_Zakaz", "Номер заказа"))
        self.radioButton_2.setText(_translate("Form_Filter_Zakaz", "Название"))
        self.radioButton_3.setText(_translate("Form_Filter_Zakaz", "Статус"))
        self.radioButton_4.setText(_translate("Form_Filter_Zakaz", "Дата доставки"))
