# Form implementation generated from reading ui file 'FormProductInZakaz.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Product_In_Zakaz(object):
    def setupUi(self, Form_Product_In_Zakaz):
        Form_Product_In_Zakaz.setObjectName("Form_Product_In_Zakaz")
        Form_Product_In_Zakaz.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Product_In_Zakaz.resize(400, 246)
        Form_Product_In_Zakaz.setFixedSize(400,246)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Product_In_Zakaz.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Product_In_Zakaz.setWindowIcon(icon)
        self.comboBox = QtWidgets.QComboBox(parent=Form_Product_In_Zakaz)
        self.comboBox.setGeometry(QtCore.QRect(30, 70, 351, 26))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(parent=Form_Product_In_Zakaz)
        self.label.setGeometry(QtCore.QRect(40, 40, 60, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(parent=Form_Product_In_Zakaz)
        self.spinBox.setGeometry(QtCore.QRect(30, 140, 351, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(999)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(parent=Form_Product_In_Zakaz)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 141, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Product_In_Zakaz)
        self.pushButton.setGeometry(QtCore.QRect(140, 200, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form_Product_In_Zakaz)
        QtCore.QMetaObject.connectSlotsByName(Form_Product_In_Zakaz)

    def retranslateUi(self, Form_Product_In_Zakaz):
        _translate = QtCore.QCoreApplication.translate
        Form_Product_In_Zakaz.setWindowTitle(_translate("Form_Product_In_Zakaz", "Товар"))
        self.label.setText(_translate("Form_Product_In_Zakaz", "Товар"))
        self.label_2.setText(_translate("Form_Product_In_Zakaz", "Кол-во товара"))
        self.pushButton.setText(_translate("Form_Product_In_Zakaz", "Внести"))
