# Form implementation generated from reading ui file 'FormUpdateOffcial.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Update_Official(object):
    def setupUi(self, Form_Update_Official):
        Form_Update_Official.setObjectName("Form_Update_Official")
        Form_Update_Official.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Update_Official.resize(400, 300)
        Form_Update_Official.setFixedSize(400,300)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Update_Official.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Update_Official.setWindowIcon(icon)
        Form_Update_Official.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.label = QtWidgets.QLabel(parent=Form_Update_Official)
        self.label.setGeometry(QtCore.QRect(20, 80, 181, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Update_Official)
        self.textEdit.setGeometry(QtCore.QRect(20, 120, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Update_Official)
        self.pushButton.setGeometry(QtCore.QRect(150, 220, 113, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form_Update_Official)
        QtCore.QMetaObject.connectSlotsByName(Form_Update_Official)

    def retranslateUi(self, Form_Update_Official):
        _translate = QtCore.QCoreApplication.translate
        Form_Update_Official.setWindowTitle(_translate("Form_Update_Official", "Форма обновления записи"))
        self.label.setText(_translate("Form_Update_Official", "Наименование должности"))
        self.pushButton.setText(_translate("Form_Update_Official", "Обновить"))
