# Form implementation generated from reading ui file 'FormInsertStaff.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Staff(object):
    def setupUi(self, Form_Staff):
        Form_Staff.setObjectName("Form_Staff")
        Form_Staff.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Staff.resize(400, 551)
        Form_Staff.setFixedSize(400,551)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Staff.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Staff.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form_Staff)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Staff)
        self.textEdit.setGeometry(QtCore.QRect(20, 70, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Staff)
        self.pushButton.setGeometry(QtCore.QRect(140, 500, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=Form_Staff)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 181, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Form_Staff)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 160, 361, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Form_Staff)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 181, 16))
        self.label_3.setObjectName("label_3")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=Form_Staff)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 260, 361, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=Form_Staff)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 181, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=Form_Staff)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 350, 361, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_5 = QtWidgets.QLabel(parent=Form_Staff)
        self.label_5.setGeometry(QtCore.QRect(20, 410, 181, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(parent=Form_Staff)
        self.comboBox.setGeometry(QtCore.QRect(20, 440, 361, 31))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Form_Staff)
        QtCore.QMetaObject.connectSlotsByName(Form_Staff)

    def retranslateUi(self, Form_Staff):
        _translate = QtCore.QCoreApplication.translate
        Form_Staff.setWindowTitle(_translate("Form_Staff", "Добавление записи"))
        self.label.setText(_translate("Form_Staff", "ФИО сотрудника"))
        self.pushButton.setText(_translate("Form_Staff", "Добавить"))
        self.label_2.setText(_translate("Form_Staff", "Адрес проживания"))
        self.label_3.setText(_translate("Form_Staff", "Паспорт"))
        self.label_4.setText(_translate("Form_Staff", "Телефон"))
        self.label_5.setText(_translate("Form_Staff", "Должность"))
