# Form implementation generated from reading ui file 'FormFilterClient.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets

basedir = os.path.dirname(__file__)
class Ui_Form_Filter_Client(object):
    def setupUi(self, Form_Filter_Client):
        Form_Filter_Client.setObjectName("Form_Filter_Client")
        Form_Filter_Client.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Filter_Client.resize(400, 190)
        Form_Filter_Client.setFixedSize(400,190)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        Form_Filter_Client.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "icons", "logo.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Filter_Client.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form_Filter_Client)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form_Filter_Client)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 361, 31))
        self.textEdit.setStyleSheet("\n"
"\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form_Filter_Client)
        self.pushButton.setGeometry(QtCore.QRect(40, 130, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form_Filter_Client)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 130, 113, 32))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(23, 92, 157);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(11, 48, 84);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form_Filter_Client)
        QtCore.QMetaObject.connectSlotsByName(Form_Filter_Client)

    def retranslateUi(self, Form_Filter_Client):
        _translate = QtCore.QCoreApplication.translate
        Form_Filter_Client.setWindowTitle(_translate("Form_Filter_Client", "Фильтр"))
        self.label.setText(_translate("Form_Filter_Client", "Название"))
        self.pushButton.setText(_translate("Form_Filter_Client", "Применить"))
        self.pushButton_2.setText(_translate("Form_Filter_Client", "Сбросить"))
